POST http://localhost:8003/access/register
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJ1c2VyIiwidXNlcklkIjoiODE4ZDJjMWYtODkzMS00ZDZjLTlkZGMtMjFhNzQ0MThlZDAzIiwiYnVpbGRpbmdJZCI6Ijk4NWNhNWE1LTIxNTktNDNkOS05NDE4LThlM2E3MzRlYTYyMiIsInJlc2lkZW5jeUlkIjoiNmZiZmYxMDUtMWZiYi00OTQ5LTk2NmUtOGM1M2ExYWI5MzVlIiwicmVzaWRlbmN5TmFtZSI6IkFwdCAwMkEiLCJwZXJtaXNzaW9ucyI6WyJAVmlzaXRvcjpWaWV3Il0sImlhdCI6MTc3OTc2MTIwOCwiZXhwIjoxNzc5NzY0ODA4fQ.kovYkkUtHL0N0X57ZuIJLCIi-0YOcQrBJCEv_AYM6oE 

{
    "rg": "123456789",
    "cpf": "12345678900",
    "name": "João Teste",
    "entryAt": "2024-06-01T10:00:00Z"
}
###
GET http://localhost:8003/access
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJ1c2VyIiwidXNlcklkIjoiODE4ZDJjMWYtODkzMS00ZDZjLTlkZGMtMjFhNzQ0MThlZDAzIiwiYnVpbGRpbmdJZCI6Ijk4NWNhNWE1LTIxNTktNDNkOS05NDE4LThlM2E3MzRlYTYyMiIsInJlc2lkZW5jeUlkIjoiNmZiZmYxMDUtMWZiYi00OTQ5LTk2NmUtOGM1M2ExYWI5MzVlIiwicmVzaWRlbmN5TmFtZSI6IkFwdCAwMkEiLCJwZXJtaXNzaW9ucyI6WyJAVmlzaXRvcjpWaWV3Il0sImlhdCI6MTc3OTc2MTIwOCwiZXhwIjoxNzc5NzY0ODA4fQ.kovYkkUtHL0N0X57ZuIJLCIi-0YOcQrBJCEv_AYM6oE

