POST http://localhost:8002/packages
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiOGNjMmY1NGItN2FkZS00ZDE4LTllMGYtNzc0ODQxODgxNmNiIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3OTIzOTQzNCwiZXhwIjoxNzc5MjQzMDM0fQ.mmfFjQ_esKu5vyjL29EG6muKsV4eQ6PuJ0XCL66X_TU

{
    "residencyId": "6fbff105-1fbb-4949-966e-8c53a1ab935e",
    "description": "Pacote Amazon - Livro de Node.js - Teste"
}

###
GET http://localhost:8002/packages/view
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiOGNjMmY1NGItN2FkZS00ZDE4LTllMGYtNzc0ODQxODgxNmNiIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3OTI0NTQ2NiwiZXhwIjoxNzc5MjQ5MDY2fQ.KjfdwfT8y_Df1FH3ITXo3kSQFFvM6sOFlpF2Y8RYKAI
###
PUT http://localhost:8002/packages
Content-Type: application/json
Authorization 