GET http://localhost:8000/auth
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiOTNjNjY5MTEtZmRhMi00MDRhLWEwYzUtNjJiNDBhOGJkNDgzIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3ODY0MTMxNSwiZXhwIjoxNzc4NjQ0OTE1fQ.p8RWRHtOC9cfMuRrZgcoeZN0arJBSyxSeqXZrUAz1tY


###
PUT http://localhost:8000/user/ecaf088d-f0ab-4256-abcf-e3765b2a62f7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiYjJmYzJjMDgtYjQ5Zi00NzY0LWExNGMtYzIxZTUzYjQzZTg0IiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3ODgwNTY0NywiZXhwIjoxNzc4ODA5MjQ3fQ.9JIAJUf4p8YmKoxdhqfiVluoRG39nHvfQcYc5EuWitM

{
    "name": "João Teste",
  "residencyId": "91d66671-1b6f-4db4-991e-e600302d2b1d",
  "buildingId": "89c3d15f-6be4-4ff3-9604-5f1b9ffa5b92",
  "permissions": [
    "@Visitor:View"
  ],
  "accountId": "b2fc2c08-b49f-4764-a14c-c21e53b43e84"
}

###
POST http://localhost:8000/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiYjJmYzJjMDgtYjQ5Zi00NzY0LWExNGMtYzIxZTUzYjQzZTg0IiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3ODgwNTY0NywiZXhwIjoxNzc4ODA5MjQ3fQ.9JIAJUf4p8YmKoxdhqfiVluoRG39nHvfQcYc5EuWitM

{
  "name": "João Teste",
  "residencyId": "91d66671-1b6f-4db4-991e-e600302d2b1d",
  "buildingId": "89c3d15f-6be4-4ff3-9604-5f1b9ffa5b92",
  "permissions": [
    "@Visitor:Create"
  ],
  "accountId": "b2fc2c08-b49f-4764-a14c-c21e53b43e84"
}