GET http://localhost:8000/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiOTNjNjY5MTEtZmRhMi00MDRhLWEwYzUtNjJiNDBhOGJkNDgzIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsImlhdCI6MTc3ODY0MTMxNSwiZXhwIjoxNzc4NjQ0OTE1fQ.p8RWRHtOC9cfMuRrZgcoeZN0arJBSyxSeqXZrUAz1tY


###
PUT http://localhost:8000/user/818d2c1f-8931-4d6c-9ddc-21a74418ed03
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJ1c2VyIiwidXNlcklkIjoiODE4ZDJjMWYtODkzMS00ZDZjLTlkZGMtMjFhNzQ0MThlZDAzIiwiYnVpbGRpbmdJZCI6Ijk4NWNhNWE1LTIxNTktNDNkOS05NDE4LThlM2E3MzRlYTYyMiIsInJlc2lkZW5jeUlkIjoiNmZiZmYxMDUtMWZiYi00OTQ5LTk2NmUtOGM1M2ExYWI5MzVlIiwicmVzaWRlbmN5TmFtZSI6IkFwdCAwMkEiLCJwZXJtaXNzaW9ucyI6WyJAVmlzaXRvcjpWaWV3IiwiQERlbGl2ZXJ5OkNyZWF0ZSJdLCJpYXQiOjE3ODAwMjIzNDAsImV4cCI6MTc4MDAyNTk0MH0.Q3gNayk9l2KOwlr5GSG8y_n1szbyi3TQal6vMGEejz0

{
    "name": "João Teste",
    "residencyId": "6fbff105-1fbb-4949-966e-8c53a1ab935e",
    "buildingId": "985ca5a5-2159-43d9-9418-8e3a734ea622",
    "permissions": [
      "@Visitor:View",
      "@Delivery:ViewResidency",
      "@Delivery:Create"
    ],
    "accountId": "8cc2f54b-7ade-4d18-9e0f-7748418816cb"
}

###
POST http://localhost:8000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiMzMxNzIxOWItZWQxMC00NGM1LThkMTktMDIyMDZjMmE4MWViIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJpYXQiOjE3ODAwMjQxMTUsImV4cCI6MTc4MDAyNzcxNX0.yuGX1w9OIJlMHTJTOF8Vs7JaUjfvPZRGV0aj4eMmgfw

{
  "name": "João Teste",
  "residencyId": "bdac1dbc-7ad3-4cd4-bb37-fae0f23bfa1f",
  "buildingId": "985ca5a5-2159-43d9-9418-8e3a734ea622",
  "permissions": [
    "@Visitor:Create",
    "@Delivery:ViewResidency"
  ],
  "accountId": "8cc2f54b-7ade-4d18-9e0f-7748418816cb"
}
###
PUT http://localhost:8000/user/d39f78e0-0e6f-41a3-a196-d30596dad779
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbktpbmQiOiJhY2NvdW50IiwiYWNjb3VudElkIjoiMzMxNzIxOWItZWQxMC00NGM1LThkMTktMDIyMDZjMmE4MWViIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJpYXQiOjE3ODAwMjQxMTUsImV4cCI6MTc4MDAyNzcxNX0.yuGX1w9OIJlMHTJTOF8Vs7JaUjfvPZRGV0aj4eMmgfw

{
  "name": "Teste",
  "residencyId": "bdac1dbc-7ad3-4cd4-bb37-fae0f23bfa1f",
  "buildingId": "985ca5a5-2159-43d9-9418-8e3a734ea622",
  "permissions": [
    "@Visitor:View",
    "@Delivery:ViewResidency",
    "@Delivery:Create",
    "@Delivery:ViewBuilding"
  ],
  "accountId": "3317219b-ed10-44c5-8d19-02206c2a81eb"
}
