POST http://localhost:8001/auth/account
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "phone": "119876543",
  "password": "123"
}

###
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email": "joao@teste.com",
  "password": "123"
}

###
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123"
}