GET http://localhost:8000/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3MzYwNDEyLTBmNWEtNGQzNy04MTlkLTQ4NjExNzVmNzk2MyIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwiaWF0IjoxNzc3NDIzNTE2LCJleHAiOjE3Nzc0MjcxMTZ9.g50g8OzKSOKRnvpnVCGaXmmiMMqDUhW63Mu1Oz6r1e8